language: objective-c

install:
- sh ./.deploy/travis/py_set_up.sh

script:
- python ./.deploy/travis/main_parser.py

env:
  global:
    secure: ZlqmyMdR+STh4+oK4G3K1apoNNUfW9dZewusrnOOBNg3/TbL55hTBe78Eag+YV/s4BaBIvX48yU+jCKM6jABKJFlUVOf/Q1v+mJL0CHZvvL0qdk3FS7lQc6ENfEVSzRksu128/DTiDcq2VOexm/RiHc8FYPrEIhwzD0dmBBtjYs/FG3yGKyN2MZMvVZvq/KAbpizjNP8zksp2USWGLfOX5kMSH+VDelqW3XS0aSMAeByQ7txsEKGLD9duNk0yAfuO3tXubcM7TyTIgPU5Blk6iAAykwqXG8NDxfGlou3yjFphtoHE3L7vYkVVIAKgvuaRWXfpZ2E4uEundFxOf+UIZ7tEgiVE6r7OXiS7aHKRT951htLht/Ovr4McH5bsZcU5w61f3IgDSMtgqZ6WQjmrypEx5e1a5alLN3Oxq094tDWskh9cE+FB0qjxSY3JDb/MnzZkg/JuQir4tzj7dOUdYWc42XtQZ/iZgUXBVppceNoFzatcXS243I3t8Mo/emma/tKJsA2mzaFk3qCJlod/RB51zDGVeh18nnciJCPTHIPvjpMqXKonxGm6gHhCOLWoc4ZniGouvXE/eiFqy/E/NawwRqAel71NLlPfPcUhyZPIscsg1KbeqqlM78NGSZOJgqtFzuvky6cFNrkBEprzm9+pSzOLYnmbZu9w7CkWiY=

addons:
  sonarqube:
    organization: odmehb-github
    token:
      secure: ZlqmyMdR+STh4+oK4G3K1apoNNUfW9dZewusrnOOBNg3/TbL55hTBe78Eag+YV/s4BaBIvX48yU+jCKM6jABKJFlUVOf/Q1v+mJL0CHZvvL0qdk3FS7lQc6ENfEVSzRksu128/DTiDcq2VOexm/RiHc8FYPrEIhwzD0dmBBtjYs/FG3yGKyN2MZMvVZvq/KAbpizjNP8zksp2USWGLfOX5kMSH+VDelqW3XS0aSMAeByQ7txsEKGLD9duNk0yAfuO3tXubcM7TyTIgPU5Blk6iAAykwqXG8NDxfGlou3yjFphtoHE3L7vYkVVIAKgvuaRWXfpZ2E4uEundFxOf+UIZ7tEgiVE6r7OXiS7aHKRT951htLht/Ovr4McH5bsZcU5w61f3IgDSMtgqZ6WQjmrypEx5e1a5alLN3Oxq094tDWskh9cE+FB0qjxSY3JDb/MnzZkg/JuQir4tzj7dOUdYWc42XtQZ/iZgUXBVppceNoFzatcXS243I3t8Mo/emma/tKJsA2mzaFk3qCJlod/RB51zDGVeh18nnciJCPTHIPvjpMqXKonxGm6gHhCOLWoc4ZniGouvXE/eiFqy/E/NawwRqAel71NLlPfPcUhyZPIscsg1KbeqqlM78NGSZOJgqtFzuvky6cFNrkBEprzm9+pSzOLYnmbZu9w7CkWiY=
      branches:
      - master
      - development

script:
# other script steps might be done before running the actual SonarQube analysis
- sonar-scanner
